name: Release

on:
  push:
    tags:
      - 'v1.*.*'
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-publish:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          # macOS targets
          - x86_64-apple-darwin     # Intel Mac (10.7+)
          - aarch64-apple-darwin    # Apple Silicon (11.0+, M1/M2/M3)

    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      
      - name: Configure cargo for GitHub Packages
        run: |
          mkdir -p ~/.cargo
          cat >> ~/.cargo/config.toml << EOF
          [registries.github]
          index = "https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}-index.git"
          token = "${{ secrets.GITHUB_TOKEN }}"

          [registry]
          default = "github"
          EOF
      
      - name: Build for ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }} --verbose
      
      - name: Run tests for ${{ matrix.target }}
        run: |
          # For aarch64 on Intel runner, we can use Rosetta 2
          if [[ "${{ matrix.target }}" == "aarch64-apple-darwin" ]]; then
            echo "Running tests with architecture translation (may be slower)"
          fi
          cargo test --target ${{ matrix.target }} --verbose
      
      - name: Package binary for ${{ matrix.target }}
        run: |
          mkdir -p dist/${{ matrix.target }}
          
          # Copy binaries to distribution directory
          cp target/${{ matrix.target }}/release/* dist/${{ matrix.target }}/
          
          # Create archive
          cd dist && tar -czf ${{ matrix.target }}.tar.gz ${{ matrix.target }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: dist/${{ matrix.target }}.tar.gz
          
      - name: Publish to GitHub Packages
        run: |
          cargo publish --target ${{ matrix.target }} --registry github
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Create GitHub release with all artifacts
  create-release:
    needs: build-and-publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}